# Generated by Django 5.2.3 on 2025-06-23 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_username", models.CharField(max_length=150, unique=True)),
                ("user_password", models.CharField(max_length=128)),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("batch", models.CharField(max_length=10)),
                ("session", models.CharField(max_length=20)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("department", models.CharField(max_length=100)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_approved", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                ("code_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
            ],
        ),
    ]
