# Generated by Django 5.2.3 on 2025-07-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_id",
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
