# Generated by Django 5.2.3 on 2025-06-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_is_verified_user_verification_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verification_token",
        ),
        migrations.AddField(
            model_name="user",
            name="code_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
