# Generated by Django 5.2.3 on 2025-06-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_club_alter_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_superadmin_post",
            field=models.BooleanField(default=False),
        ),
    ]
