# Generated by Django 5.2.3 on 2025-06-21 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("category", models.CharField(max_length=255)),
                ("date_established", models.DateField()),
                ("constitution", models.TextField(blank=True)),
                ("mission_and_vision", models.TextField(blank=True)),
                ("membership_rules", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("club_moto", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="club_logos/"),
                ),
                (
                    "cover_photo",
                    models.ImageField(blank=True, null=True, upload_to="club_covers/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubAdvisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisors",
                        to="clubs.club",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club_username", models.CharField(max_length=150, unique=True)),
                ("club_password", models.CharField(max_length=128)),
                ("club_name", models.CharField(max_length=255)),
                ("club_category", models.CharField(max_length=255)),
                ("date_established", models.DateField()),
                ("club_moto", models.CharField(blank=True, max_length=255)),
                ("president_name", models.CharField(max_length=255)),
                ("president_student_id", models.CharField(max_length=50)),
                ("president_email", models.EmailField(max_length=254)),
                ("president_phone", models.CharField(max_length=20)),
                ("president_session", models.CharField(max_length=20)),
                ("president_department", models.CharField(max_length=255)),
                ("secretary_name", models.CharField(max_length=255)),
                ("secretary_student_id", models.CharField(max_length=50)),
                ("secretary_email", models.EmailField(max_length=254)),
                ("secretary_phone", models.CharField(max_length=20)),
                ("secretary_session", models.CharField(max_length=20)),
                ("secretary_department", models.CharField(max_length=255)),
                ("organizing_secretary_name", models.CharField(max_length=255)),
                ("organizing_secretary_student_id", models.CharField(max_length=50)),
                ("organizing_secretary_email", models.EmailField(max_length=254)),
                ("organizing_secretary_phone", models.CharField(max_length=20)),
                ("organizing_secretary_session", models.CharField(max_length=20)),
                ("organizing_secretary_department", models.CharField(max_length=255)),
                ("other_executive_members", models.TextField(blank=True)),
                ("club_constitution", models.TextField(blank=True)),
                ("mission_and_vision", models.TextField(blank=True)),
                ("membership_rules", models.TextField(blank=True)),
                ("advisor_name", models.CharField(blank=True, max_length=255)),
                ("advisor_contact", models.CharField(blank=True, max_length=255)),
                (
                    "advisor_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "advisor_department",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("facebook_link", models.URLField(blank=True)),
                ("instagram_link", models.URLField(blank=True)),
                ("linkedin_link", models.URLField(blank=True)),
                ("youtube_link", models.URLField(blank=True)),
                ("website_link", models.URLField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_club",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clubs.club",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="clubs.club",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("student_id", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("session", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "department",
                    models.CharField(default="Not Specified", max_length=255),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("president", "President"),
                            ("secretary", "Secretary"),
                            ("organizing_secretary", "Organizing Secretary"),
                            ("general_member", "General Member"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_date", models.DateField(default=django.utils.timezone.now)),
                ("leave_date", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="member_photos/"
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "unique_together": {("club", "student_id")},
            },
        ),
    ]
