# Generated by Django 5.2.3 on 2025-06-21 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("student_id", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("session", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "department",
                    models.CharField(default="Not Specified", max_length=255),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="member_photos/"
                    ),
                ),
            ],
            options={
                "unique_together": {("student_id", "email")},
            },
        ),
        migrations.CreateModel(
            name="ClubMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roles", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("joined_date", models.DateField(default=django.utils.timezone.now)),
                ("leave_date", models.DateField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="clubs.club",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="clubs.member",
                    ),
                ),
            ],
            options={
                "unique_together": {("member", "club")},
            },
        ),
        migrations.DeleteModel(
            name="ClubMember",
        ),
    ]
