# Generated by Django 5.2.3 on 2025-07-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_requestedmember_delete_clubmemberrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestedmember",
            name="student_id",
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
