# Generated by Django 5.2.3 on 2025-06-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_clubmemberrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubadvisor",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="advisor_photos/"),
        ),
    ]
