# Generated by Django 5.2.3 on 2025-07-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_clubgallery"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClubGallery",
        ),
    ]
