# Generated by Django 5.2.3 on 2025-07-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_clubnotice"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubnotice",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="clubnotice",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="club_notices/"),
        ),
    ]
