# Generated by Django 5.2.3 on 2025-07-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0008_clubnotice_content_alter_clubnotice_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClubNotice",
        ),
    ]
