# Generated by Django 5.2.3 on 2025-07-06 20:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0009_delete_clubnotice"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Notice Title"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated URL-friendly identifier",
                        max_length=300,
                        unique=True,
                        verbose_name="URL Slug",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Notice Content"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Optional file attachment (PDF, Word, Excel, Image)",
                        null=True,
                        upload_to="club_notices/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "txt",
                                ]
                            )
                        ],
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("general", "General Notice"),
                            ("event", "Event Announcement"),
                            ("meeting", "Meeting Notice"),
                            ("urgent", "Urgent Announcement"),
                            ("achievement", "Club Achievement"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Notice Type",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Keep this notice at the top of lists",
                        verbose_name="Pin to Top",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Visible to non-members",
                        verbose_name="Public Notice",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the notice should become visible",
                        verbose_name="Publish Date",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notice should be automatically archived",
                        null=True,
                        verbose_name="Expiration Date",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Club Notice",
                "verbose_name_plural": "Club Notices",
                "ordering": ["-is_pinned", "-publish_date"],
                "get_latest_by": "publish_date",
                "indexes": [
                    models.Index(
                        fields=["publish_date"], name="clubs_clubn_publish_80e942_idx"
                    ),
                    models.Index(
                        fields=["is_pinned"], name="clubs_clubn_is_pinn_55a32c_idx"
                    ),
                    models.Index(
                        fields=["notice_type"], name="clubs_clubn_notice__60b82b_idx"
                    ),
                ],
            },
        ),
    ]
